"""
01_setup_weaviate.py
--------------------
Creates the LegalChunk collection in Weaviate with:
- Hybrid search enabled (BM25 + dense vector)
- All metadata properties for filtering
Run this ONCE before ingesting any data.
"""

import weaviate
import weaviate.classes as wvc
from weaviate.classes.config import Configure, Property, DataType, VectorDistances
from dotenv import load_dotenv
import os

load_dotenv()

def setup_weaviate():
    # Connect to local Weaviate
    client = weaviate.connect_to_local(
        host="localhost",
        port=8080,
    )

    try:
        print("Connected to Weaviate:", client.is_ready())

        collection_name = "LegalChunk"

        # Delete existing collection if rebuilding
        if client.collections.exists(collection_name):
            print(f"Collection '{collection_name}' already exists.")
            user_input = input("Delete and recreate? (yes/no): ").strip().lower()
            if user_input == "yes":
                client.collections.delete(collection_name)
                print("Deleted existing collection.")
            else:
                print("Keeping existing collection. Exiting.")
                return

        # Create the collection
        client.collections.create(
            name=collection_name,

            # Vectorizer: none — we supply our own vectors
            # (generated by sentence-transformers locally)
            vectorizer_config=Configure.Vectorizer.none(),

            # Vector index: HNSW for fast approximate nearest neighbour search
            vector_index_config=Configure.VectorIndex.hnsw(
                distance_metric=VectorDistances.COSINE
            ),

            # Properties (metadata fields for filtering)
            properties=[
                Property(
                    name="text",
                    data_type=DataType.TEXT,
                    description="The actual legal text chunk"
                ),
                Property(
                    name="act_name",
                    data_type=DataType.TEXT,
                    description="Name of the act e.g. Muslim Family Laws Ordinance 1961"
                ),
                Property(
                    name="section_number",
                    data_type=DataType.TEXT,
                    description="Section or sub-section number e.g. Section 7"
                ),
                Property(
                    name="topic_tag",
                    data_type=DataType.TEXT,
                    description="Legal topic: divorce, custody, maintenance, dowry, nikah"
                ),
                Property(
                    name="province",
                    data_type=DataType.TEXT,
                    description="Province: Federal, Punjab, Sindh, KPK, Balochistan"
                ),
                Property(
                    name="language",
                    data_type=DataType.TEXT,
                    description="Language of chunk: en or ur"
                ),
                Property(
                    name="year",
                    data_type=DataType.INT,
                    description="Year the act was enacted or amended"
                ),
                Property(
                    name="source_url",
                    data_type=DataType.TEXT,
                    description="URL or file path of source document"
                ),
                Property(
                    name="is_case_law",
                    data_type=DataType.BOOL,
                    description="True if this is a court judgement, False if legislation"
                ),
                Property(
                    name="chunk_type",
                    data_type=DataType.TEXT,
                    description="parent or child — indicates chunk hierarchy level"
                ),
                Property(
                    name="parent_id",
                    data_type=DataType.TEXT,
                    description="UUID of the parent chunk (empty string for parents)"
                ),
            ]
        )

        print(f"\nCollection '{collection_name}' created successfully.")
        print("Properties set:", [
            "text", "act_name", "section_number", "topic_tag",
            "province", "language", "year", "source_url", "is_case_law",
            "chunk_type", "parent_id"
        ])

    finally:
        client.close()
        print("\nWeaviate connection closed.")


if __name__ == "__main__":
    setup_weaviate()

